name: Compile and publish TGE

on: [push]

jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Compile
        run: |
          ./scripts/compile_tge.sh
          ./scripts/compile_ttge.sh
          ./scripts/compile_tmge.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Jars
          path: jars
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: jars/*.jar
          name: ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
